language: node_js
node_js:
  - 10
services:
  - docker 
stages:
  - name: deploy
    if: branch == main AND type = push
jobs:
  include:
    - stage: deploy
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export SAMPLE_TRAVIS_REPO=kotid/sample-travis
        - docker build -f Dockerfile -t $SAMPLE_TRAVIS_REPO:build-$TRAVIS_BUILD_NUMBER -t $SAMPLE_TRAVIS_REPO:latest .
        - docker push $SAMPLE_TRAVIS_REPO:build-$TRAVIS_BUILD_NUMBER
        - docker push $SAMPLE_TRAVIS_REPO:latest
          
