language: node_js
node_js:
  - 10
services:
  - docker 
stages:
  - name: deploy
    if: branch == main AND type = push
jobs:
  include:
    - stage: deploy
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export SAMPLE_TRAVIS_REPO=kotid/sample-travis
        - bash unittest
