apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: fluxv2
  labels:
    app: nginx
spec:
  replicas: 1 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: fluxv2-pods-sa
      containers:
      - name: nginx-image
        image: us-west1-docker.pkg.dev/kcs-ace2/nginx/nginx:build-01
        ports:
        - containerPort: 80
