apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app2
  annotations: # Flux annotions are not required for prod as we have to change the build number manually
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.nginx: glob:build-*
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: flux-pods-sa
      containers:
      - name: nginx
        image: us-west1-docker.pkg.dev/kcs-ace2/oct-app/nginx:build-1
        ports:
        - containerPort: 80